
test:
  before_script:
    - echo "Running before_script for test job..."
  script:
    - echo "Running main script for test job..."
  after_script:
    - echo "Running after_script for test job..."


build_image:
  script:
    - echo "Building Docker image..."

push_image:
  script:
    - echo "Logging into Docker registry..."
    - echo "Pushing Docker image..."
